# Generated by Django 5.1.2 on 2024-10-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
    ]
